
[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[window]
opacity = 0.99
blur = true
decorations = "Buttonless"
padding = { x = 5, y = 5 }

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]  			# Perfectly work for macOS (Fish Shell + Tmux)

